translations = {
    'English': {
        'nav_title': "Navigation",
        'app_desc': "A powerful tool for visualized Machine Learning.",
        'nav_data': "Data Upload",
        'nav_analysis': "Analysis",
        'nav_model': "Model Zoo",
        'nav_opt': "Optimization",
        'nav_predict': "Prediction",
        'nav_results': "Results",
        
        'header_data': "Data Central 📂",
        'header_analysis': "Exploratory Analysis 🔍",
        'header_model': "Model Training 🧠",
        'header_opt': "Auto-Tuning 🚀",
        'header_opt': "Auto-Tuning 🚀",
        'header_predict': "Model Prediction 🔮",
        'header_results': "Evaluation Results 📊",
        'header_results': "Evaluation Results 📊",
        'header_hea': "HEA & Cermets Analysis 🧪",
        'header_library': "Material Library 📚",
        
        'nav_hea': "HEA/Cermets",
        
        'upload_label': "Upload your dataset (CSV/Excel)",
        'data_preview': "Data Preview",
        'data_info': "Data Info",
        'stats': "Descriptive Statistics",
        'preprocessing': "Preprocessing",
        'handle_missing': "Handle Missing Values",
        'apply_missing': "Apply Missing Value Handling",
        'missing_handled': "Missing values handled.",
        'load_success': "Data loaded successfully.",
        'load_error': "Error loading data: {}",
        
        # Dataset Persistence
        'save_dataset': "Save Dataset",
        'dataset_name': "Dataset Name (e.g., my_data)",
        'save_btn': "Save to Disk",
        'save_success': "Dataset saved successfully!",
        'saved_datasets': "Saved Datasets 💾",
        'load_btn': "Load",
        'delete_btn': "Delete",
        'confirm_delete': "Are you sure you want to delete '{}'?",
        'delete_success': "Dataset deleted successfully.",
        'no_saved': "No saved datasets found.",
        
        'tab_dist': "Distributions",
        'tab_corr': "Correlation",
        'tab_rel': "Relationships",
        'select_col_dist': "Select Column for Distribution",
        'not_enough_data': "Not enough numeric data for correlation.",
        'x_axis': "X Axis",
        'y_axis': "Y Axis",
        'color_opt': "Color (Optional)",
        'color_opt': "Color (Optional)",
        'warning_upload': "Please upload data first.",
        
        # HEA Page
        'hea_intro': "Analyze High-Entropy Alloys and Cermets by calculating key theoretical parameters.",
        'mode_single': "Single Composition Analysis",
        'mode_batch': "Batch Analysis (CSV/Excel)",
        'enter_formula': "Enter Chemical Formula (e.g., AlCoCrFeNi)",
        'calc_btn': "Calculate Properties",
        'calc_error': "Could not parse formula. Please check element symbols.",
        'calc_results': "Calculation Results",
        'batch_upload': "Upload Formula File",
        'select_formula_col': "Select Formula Column",
        'process_batch': "Process Batch",
        'download_results': "Download Results (CSV)",
        
        # Model Names
        
        # Model Names
        'model_lr': 'Linear Regression',
        'model_ridge': 'Ridge',
        'model_lasso': 'Lasso',
        'model_rf': 'Random Forest',
        'model_xgb': 'XGBoost',
        'model_svr': 'SVR',
        'model_logr': 'Logistic Regression',
        'model_dt': 'Decision Tree',
        'model_svc': 'SVC',
        'model_lgbm': 'LightGBM',
        'model_cb': 'CatBoost',
        'model_kmeans': 'K-Means',
        'task_clustering': 'Clustering',
        'model_stacking': 'Stacking Regressor',
        'stacking_desc': 'Ensemble method using XGBoost, Random Forest, SVR, and Ridge as base learners, with Ridge as the meta-learner.',
        
        # Missing Methods
        'miss_drop': 'Drop rows',
        'miss_mean': 'Fill with Mean',
        'miss_median': 'Fill with Median',
        'miss_mode': 'Fill with Mode',
        
        'config': "Configuration",
        'select_target': "Select Target Variable",
        'task_type': "Task Type",
        'select_model': "Select Model",
        'hyperparams': "Hyperparameters",
        'test_size': "Test Split Size",
        'training_action': "Training Action",
        'train_btn': "Train Model",
        'training_spinner': "Preparing Data & Training...",
        'training_complete': "Training Complete!",

        'feature_selection': "Feature Selection",
        'select_features': "Select Features to Include",
        
        'opt_info': "Uses Optuna to find the best hyperparameters for your selected model structure.",
        'model_opt': "Model to Optimize",
        'n_trials': "Number of Trials",
        'start_opt': "Start Optimization",
        'opt_spinner': "Optimizing... this might take a while",
        'opt_complete': "Optimization Complete!",
        'best_params': "Best Parameters found:",
        'opt_hint': "You can now apply these parameters to the training configuration.",
        'apply_params': "Apply Tuned Parameters",
        'params_applied': "Parameters applied! Please retrain the model.",
        'warning_prep': "Please prepare data (Train a dummy model first to set split) or go to Model Zoo.",
        
        'perf_metrics': "Performance Metrics",
        'feat_imp': "Feature Importance",
        'no_model': "No model trained yet. Go to Model Zoo to train a model.",
        
        # Model Persistence
        'save_model_title': "Save Trained Model",
        'model_name_input': "Model Name",
        'save_model_btn': "Save Model",
        'save_model_success': "Model saved successfully!",
        'manage_models_title': "Manage Models (Load / Upload)",
        'upload_model_label': "Upload Model File (.joblib)",
        'saved_models_list': "Saved Models",
        'load_model_btn': "Load",
        'delete_model_btn': "Delete",
        'load_model_success': "Model loaded successfully!",
        'delete_model_success': "Model deleted successfully.",
        'confirm_delete_model': "Are you sure you want to delete '{}'?",
        'no_saved_models': "No saved models found.",
        
        # Prediction Page
        'pred_model_select': "Select Trained Model",
        'pred_mode': "Prediction Mode",
        'pred_mode_manual': "Manual Input",
        'pred_mode_batch': "Batch Prediction (File)",
        'pred_input_data': "Input Features",
        'pred_btn': "Predict",
        'pred_result': "Prediction Result",
        'pred_batch_upload': "Upload Data for Prediction",
        'pred_download': "Download Predictions",
        'pred_manual_intro': "Enter values for each feature manually.",
        'pred_batch_intro': "Upload a file (CSV/Excel) with columns matching the model features.",
        'pred_load_model_first': "Please load a model from the list first.",
        'pred_feature_mismatch': "Feature mismatch: Model expects {}. Found {}.",
        'pred_success': "Prediction successful!",
        'predict_spinner': "Predicting...",
        
        # Library Page
        'library_desc': "Reference database for mixing enthalpies, ceramic properties, and more.",
        'lib_intro': "Explore fundamental material properties and thermodynamic data.",
        'enthalpy_data': "Binary Mixing Enthalpy",
        'search_placeholder': "Search for elements (e.g., Al-Co)...",
        
        'tab_elements': "Elements Data",
        'tab_enthalpy': "Mixing Enthalpy",
        'tab_ceramic': "Ceramic Properties",
        'tab_process': "Process Parameters",
        
        'col_element': "Element",
        'col_atomic_weight': "Atomic Weight",
        'col_radius': "Atomic Radius (pm)",
        'col_vec': "VEC",
        'col_electronegativity': "Electronegativity",
        'col_melting': "Melting Point (K)",
        
        'col_compound': "Compound",
        'col_density': "Density (g/cm³)",
        'col_molar': "Molar Mass (g/mol)",
        
        'process_param': "Parameter",
        'process_desc': "Description",
        'process_range': "Typical Range",
        'param_temp': "Sintering Temperature",
        'param_time': "Sintering Time",
        'param_grain': "Grain Size",
        'param_vol': "Volume Fraction",
        
        # Single Point Analysis
        'tab_single': "Single Point Analysis",
        'header_single': "1. Design Space & Physics Analysis",
        'hea_binder_comp': "HEA Binder Composition",
        'microstructure': "Microstructure",
        'sintering_process': "Sintering Process",
        'wc_vol_frac': "WC Volume Fraction (%)",
        'grain_size_label': "Grain Size (um)",
        'temp_label': "Temperature (C)",
        'time_label': "Time (min)",
        'total_atomic_zero': "Total HEA composition cannot be zero!",
        
        'physics_output': "2. Physics Engine Output",
        'vec_help': "Valence Electron Concentration. >= 8.0 indicates FCC/Ductile.",
        'mismatch_help': "Misfit between Binder and WC.",
        'wettability_help': "0-10 Scale.",
        'homologous_help': "T_sinter / T_liquidus.",
        
        'detailed_vol_frac': "Detailed Volume Fractions",
        'phase_dist': "Phase Distribution",
        'element_dist': "Element Distribution (Total)",
        
        'ai_pred': "3. AI Performance Prediction",
        'pred_hv': "Predicted HV (Vickers)",
        'pred_k1c': "Predicted K1C (Toughness)",
        'interface_quality': "Interface Quality",

        # Literature Lab
        'lit_title': "Literature Analysis Lab",
        'lit_actions': "Actions",
        'lit_mode': "Mode",
        'lit_upload_analyze': "Upload & Analyze",
        'lit_db_view': "Database View",
        'lit_search_sim': "Search Similar Materials",
        'lit_header_upload': "Upload Literature (PDF/Text)",
        'lit_choose_file': "Choose a file",
        'lit_analyze_btn': "Analyze",
        'lit_analyzing': "Analyzing...",
        'lit_success_analysis': "Analysis Complete!",
        'lit_text_preview': "Extracted Text Preview",
        'lit_analysis_results': "Analysis Results",
        'lit_save_lib': "Save to Library",
        'lit_save_success': "Saved to extracted data library!",
        'lit_error_analysis': "Error analyzing file: {}",
        'lit_header_db': "Extracted Data Library",
        'lit_no_records': "No records found.",
        # Inverse Design
        'tab_inverse': "Inverse Design",
        'header_inverse': "4. Inverse Material Design",
        'inverse_goal': "Goal: Find compositions that satisfy HV > 1800 and K1C > 12.",
        'run_opt': "🚀 Run NSGA-II Optimization",
        'opt_running': "Running Genetic Algorithm...",
        'opt_success': "Optimization Complete! Found {} Pareto optimal solutions.",
        'pareto_front': "Pareto Front (HV vs K1C)",
    },
    '简体中文': {
        'nav_title': "导航",
        'app_desc': "强大的可视化机器学习工具。",
        'nav_data': "数据上传",
        'nav_analysis': "探索分析",
        'nav_model': "模型训练",
        'nav_opt': "自动调优",
        'nav_predict': "模型预测",
        'nav_results': "结果展示",
        
        'header_data': "数据中心 📂",
        'header_analysis': "探索性分析 🔍",
        'header_model': "模型训练 🧠",
        'header_opt': "自动调优 🚀",
        'header_predict': "模型预测 🔮",
        'header_results': "评估结果 📊",
        'header_hea': "HEA & 金属陶瓷分析 🧪",
        'header_library': "材料资料库 📚",
        'nav_hea': "HEA/金属陶瓷",
        'nav_library': "金属陶瓷图书馆",
        
        'upload_label': "上传数据集 (CSV/Excel)",
        'data_preview': "数据预览",
        'data_info': "数据信息",
        'stats': "描述性统计",
        'preprocessing': "数据预处理",
        'handle_missing': "缺失值处理",
        'apply_missing': "执行缺失值处理",
        'missing_handled': "缺失值已处理。",
        'load_success': "数据加载成功。",
        'load_error': "数据加载失败: {}",
        
        # Dataset Persistence
        'save_dataset': "保存数据集",
        'dataset_name': "数据集名称 (例如: my_data)",
        'save_btn': "保存到本地",
        'save_success': "数据集保存成功！",
        'saved_datasets': "已保存的数据集 💾",
        'load_btn': "加载",
        'delete_btn': "删除",
        'confirm_delete': "确定要删除 '{}' 吗？",
        'delete_success': "数据集删除成功。",
        'no_saved': "暂无保存的数据集。",
        
        'tab_dist': "分布查阅",
        'tab_corr': "相关性分析",
        'tab_rel': "关系探索",
        'select_col_dist': "选择分布列",
        'not_enough_data': "数字数据不足，无法进行相关性分析。",
        'x_axis': "X 轴",
        'y_axis': "Y 轴",
        'color_opt': "颜色 (可选)",
        'color_opt': "颜色 (可选)",
        'warning_upload': "请先上传数据。",
        
        # HEA Page
        'hea_intro': "计算熵合金及金属陶瓷的关键理论参数。",
        'mode_single': "单组分分析",
        'mode_batch': "批量分析 (CSV/Excel)",
        'enter_formula': "输入化学式 (例如: AlCoCrFeNi)",
        'calc_btn': "计算属性",
        'calc_error': "无法解析化学式，请检查元素符号。",
        'calc_results': "计算结果",
        'batch_upload': "上传化学式文件",
        'select_formula_col': "选择化学式列",
        'process_batch': "批量处理",
        'download_results': "下载结果 (CSV)",
        
        # Model Names
        'model_lr': '线性回归 (Linear Regression)',
        'model_ridge': '岭回归 (Ridge)',
        'model_lasso': '套索回归 (Lasso)',
        'model_rf': '随机森林 (Random Forest)',
        'model_xgb': 'XGBoost',
        'model_svr': '支持向量回归 (SVR)',
        'model_logr': '逻辑回归 (Logistic Regression)',
        'model_dt': '决策树 (Decision Tree)',
        'model_svc': '支持向量机 (SVC)',
        'model_lgbm': 'LightGBM',
        'model_cb': 'CatBoost',
        'model_kmeans': 'K-Means',
        'task_clustering': '聚类 (Clustering)',
        'model_stacking': '堆叠回归 (Stacking Regressor)',
        'stacking_desc': '集成方法：使用 XGBoost, Random Forest, SVR, Ridge 作为基学习器，Ridge 作为元学习器。',
        
        # Missing Methods
        'miss_drop': '丢弃行 (Drop)',
        'miss_mean': '均值填充 (Mean)',
        'miss_median': '中位数填充 (Median)',
        'miss_mode': '众数填充 (Mode)',
        
        'config': "配置",
        'select_target': "选择目标变量",
        'task_type': "任务类型",
        'select_model': "选择模型",
        'hyperparams': "超参数",
        'test_size': "测试集比例",
        'training_action': "训练操作",
        'train_btn': "开始训练",
        'training_spinner': "数据准备与训练中...",
        'training_spinner': "数据准备与训练中...",
        'training_complete': "训练完成！",

        'feature_selection': "特征选择",
        'select_features': "选择参与训练的特征",
        
        'opt_info': "使用 Optuna 引擎为您选择的模型结构寻找最佳超参数。",
        'model_opt': "待优化模型",
        'n_trials': "尝试次数 (Trials)",
        'start_opt': "开始优化",
        'opt_spinner': "正在优化中... 这可能需要一些时间",
        'opt_complete': "优化完成！",
        'best_params': "发现的最佳参数：",
        'best_params': "发现的最佳参数：",
        'opt_hint': "您可以点击下方按钮应用这些参数。",
        'apply_params': "应用调优参数",
        'params_applied': "参数已应用！请重新点击训练按钮。",
        'warning_prep': "请先准备数据（可在模型训练页训练一个测试模型以划分数据），或者前往模型训练页。",
        
        'perf_metrics': "性能指标",
        'feat_imp': "特征重要性",
        'no_model': "尚未训练模型。请前往“模型训练”页面进行训练。",
        
        # Model Persistence
        'save_model_title': "保存训练模型",
        'model_name_input': "模型名称",
        'save_model_btn': "保存模型",
        'save_model_success': "模型保存成功！",
        'manage_models_title': "管理模型 (加载 / 上传)",
        'upload_model_label': "上传模型文件 (.joblib)",
        'saved_models_list': "已保存的模型",
        'load_model_btn': "加载",
        'delete_model_btn': "删除",
        'load_model_success': "模型加载成功！",
        'delete_model_success': "模型删除成功。",
        'confirm_delete_model': "确定要删除 '{}' 吗？",
        'no_saved_models': "暂无保存的模型。",
        
        # Prediction Page
        'pred_model_select': "选择已训练模型",
        'pred_mode': "预测模式",
        'pred_mode_manual': "手动输入",
        'pred_mode_batch': "批量预测 (文件上传)",
        'pred_input_data': "输入特征",
        'pred_btn': "开始预测",
        'pred_result': "预测结果",
        'pred_batch_upload': "上传预测数据",
        'pred_download': "下载预测结果",
        'pred_manual_intro': "请手动输入每个特征的值。",
        'pred_batch_intro': "上传包含模型所需特征的文件 (CSV/Excel)。",
        'pred_load_model_first': "请先从列表中加载一个模型。",
        'pred_feature_mismatch': "特征不匹配: 模型需要 {}. 实际找到 {}.",
        'pred_success': "预测成功！",
        'predict_spinner': "正在预测...",
        
        # Library Page
        'library_desc': "包含混合焓、陶瓷属性等参考数据库。",
        'lib_intro': "探索基础材料属性和热力学数据。",
        'enthalpy_data': "二元混合焓",
        'search_placeholder': "搜索元素 (例如: Al-Co)...",
        
        'tab_elements': "元素数据",
        'tab_enthalpy': "混合焓",
        'tab_ceramic': "陶瓷属性",
        'tab_process': "工艺参数",
        
        'col_element': "元素",
        'col_atomic_weight': "原子量",
        'col_radius': "原子半径 (pm)",
        'col_vec': "价电子浓度 (VEC)",
        'col_electronegativity': "电负性",
        'col_melting': "熔点 (K)",
        
        'col_compound': "化合物",
        'col_density': "密度 (g/cm³)",
        'col_molar': "摩尔质量 (g/mol)",
        
        'process_param': "参数",
        'process_desc': "描述",
        'process_range': "典型范围",
        'param_temp': "烧结温度",
        'param_time': "烧结时间",
        'param_grain': "晶粒尺寸",
        'param_vol': "体积分数",
        
        # Single Point Analysis
        'tab_single': "单点分析",
        'header_single': "1. 设计空间与物理分析",
        'hea_binder_comp': "HEA 粘结相成分",
        'microstructure': "微观结构",
        'sintering_process': "烧结工艺",
        'wc_vol_frac': "WC 体积分数 (%)",
        'grain_size_label': "晶粒尺寸 (um)",
        'temp_label': "温度 (C)",
        'time_label': "时间 (min)",
        'total_atomic_zero': "HEA 总成分不能为零！",
        
        'physics_output': "2. 物理引擎输出",
        'vec_help': "价电子浓度 (VEC)。>= 8.0 表示 FCC/延性。",
        'mismatch_help': "粘结相与 WC 之间的错配度。",
        'wettability_help': "0-10 标度。",
        'homologous_help': "T_sinter / T_liquidus (同系温度)。",
        
        'detailed_vol_frac': "详细体积分数",
        'phase_dist': "相分布",
        'element_dist': "元素分布 (总量)",
        
        'ai_pred': "3. AI 性能预测",
        'pred_hv': "预测 HV (维氏硬度)",
        'pred_k1c': "预测 K1C (断裂韧性)",
        'interface_quality': "界面质量",

        # Literature Lab
        'lit_title': "文献分析实验室",
        'lit_actions': "操作",
        'lit_mode': "模式",
        'lit_upload_analyze': "上传与分析",
        'lit_db_view': "数据库视图",
        'lit_search_sim': "搜索相似材料",
        'lit_header_upload': "上传文献 (PDF/文本)",
        'lit_choose_file': "选择文件",
        'lit_analyze_btn': "开始分析",
        'lit_analyzing': "正在分析...",
        'lit_success_analysis': "分析完成！",
        'lit_text_preview': "提取文本预览",
        'lit_analysis_results': "分析结果",
        'lit_save_lib': "保存到资料库",
        'lit_save_success': "已保存到提取数据资料库！",
        'lit_error_analysis': "文件分析出错: {}",
        'lit_header_db': "提取数据资料库",
        'lit_no_records': "未找到记录。",


        # Inverse Design
        'tab_inverse': "逆向设计",
        'header_inverse': "4. 逆向材料设计",
        'inverse_goal': "目标：寻找满足 HV > 1800 且 K1C > 12 的成分。",
        'run_opt': "🚀 运行 NSGA-II 优化",
        'opt_running': "正在运行遗传算法...",
        'opt_success': "优化完成！找到了 {} 个帕累托最优解。",
        'pareto_front': "帕累托前沿 (HV vs K1C)"
    }
}

def get_text(key, lang='English'):
    return translations.get(lang, translations['English']).get(key, key)
